INSERT INTO lti_permissions_ltipermission (permission, school_id, canvas_role, allow) VALUES
('im_import_files', '*', 'Account Observer', FALSE),
('im_import_files', '*', 'AccountAdmin', TRUE),
('im_import_files', '*', 'Account Admin', TRUE),
('im_import_files', '*', 'Course Head', TRUE),
('im_import_files', '*', 'Course Support Staff', TRUE),
('im_import_files', '*', 'Department Admin', TRUE),
('im_import_files', '*', 'DesignerEnrollment', TRUE),
('im_import_files', '*', 'Faculty', TRUE),
('im_import_files', '*', 'Guest', FALSE),
('im_import_files', '*', 'Harvard-Viewer', FALSE),
('im_import_files', '*', 'Help Desk', TRUE),
('im_import_files', '*', 'Librarian', FALSE),
('im_import_files', '*', 'ObserverEnrollment', FALSE),
('im_import_files', '*', 'SchoolLiaison', TRUE),
('im_import_files', '*', 'Shopper', FALSE),
('im_import_files', '*', 'StudentEnrollment', FALSE),
('im_import_files', '*', 'TaEnrollment', TRUE),
('im_import_files', '*', 'TeacherEnrollment', TRUE),
('im_import_files', '*', 'Teaching Staff', TRUE);
